src/main/java/org/openrewrite/java/logging/slf4j/Log4jToSlf4j.java
src/main/resources/META-INF/rewrite/slf4j.yml
src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4jToSlf4jTest.kt
src/test/kotlin/org/openrewrite/java/logging/slf4j/ParameterizedLogging.kt

part of https://github.com/openrewrite/rewrite-logging/issues/16
Adds content for log4j to slf4j recipe, breaks down tests further into discrete slices

Log4J to SLF4J polish details on displayName, description, decompose tests, etc.

---

src/main/java/org/openrewrite/java/logging/slf4j/Log4jToSlf4j.java
src/main/resources/META-INF/rewrite/slf4j.yml
src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4jToSlf4jTest.kt

closes https://github.com/openrewrite/rewrite-logging/issues/16
see: https://github.com/openrewrite/rewrite-logging/pull/21
Break the `Log4jToSlf4j` recipe into smaller, individual recipes.

Compose log4j-to-slf4j from smaller recipes

---

src/main/java/org/openrewrite/java/logging/slf4j/Log4jToSlf4j.java
src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4jToSlf4jTest.kt
src/test/kotlin/org/openrewrite/java/logging/slf4j/ParameterizedLoggingTest.kt

When migrating from log4j to slf4j, even in situations such as `logger.info(new Object());`, the migration should be to `logger.info("{}", new Object());` rather than `logger.info(new Object().toString());`. This avoids pitfalls of `toString()`, as well as maintains the benefits of parameterized logging being able to conditionally log based on current log level.
Closes https://github.com/openrewrite/rewrite-logging-frameworks/issues/20

Always parameterize when migrating from log4j to slf4j

---

src/main/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogback.java
src/main/java/org/openrewrite/java/logging/logback/Log4jLayoutToLogback.java
src/main/resources/META-INF/rewrite/logback.yml
src/test/kotlin/org/openrewrite/java/logging/logback/Log4jAppenderToLogbackTest.kt
src/test/kotlin/org/openrewrite/java/logging/logback/Log4jLayoutToLogbackTest.kt

Remove unnecessary type validation ignores
Use anonymous visitors instead of named static visitors
Improve descriptions on Logback recipes
Maven add dependencys for logback

Dependency additions and polish for log4j-to-logback recipes

---

src/main/java/org/openrewrite/java/logging/slf4j/CompleteExceptionLogging.java
src/test/java/org/openrewrite/java/logging/slf4j/CompleteExceptionLoggingTest.java

closes [#96 ](https://github.com/openrewrite/rewrite-logging-frameworks/issues/96)
Introduce recipe `CompleteExceptionLogging`.
It is a common mistake to call `Exception.getMessage()` when passing an exception into a log method. Not all exception types have useful messages, and even if the message is useful this omits the stack trace.
A recipe that removes calls to getMessage() within log statements would be an easy win and could be included in the logging best practices recipe.
An example case:
```java
LOG.error("An error occurred", e.getMessage());
```
to 
```java
LOG.error("An error occurred", e);
```

Introduce recipe `CompleteExceptionLogging`

---

src/main/java/org/openrewrite/java/logging/slf4j/LoggersNamedForEnclosingClass.java
src/test/java/org/openrewrite/java/logging/slf4j/CompleteExceptionLoggingTest.java
src/test/java/org/openrewrite/java/logging/slf4j/LoggersNamedForEnclosingClassTest.java

fixes: https://github.com/openrewrite/rewrite-logging-frameworks/issues/101
Do not remove `getClass()` when creating logger if the enclosing class is abstract

Fix: Loggers should be named for their enclosing classes should not replace calls to getClass()

---

src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
src/test/java/org/openrewrite/java/logging/slf4j/CompleteExceptionLoggingTest.java
src/test/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstantTest.java

fixes: https://github.com/openrewrite/rewrite-logging-frameworks/issues/95
- Add remaining arguments at the end of the log method call
- Ignore log calls where specifiers like %s and {} are combined as order might be an issue.
- improve consistency in tests
- Extract Pattern from method invocation to improve performance

Fix: Slf4jLogShouldBeConstant removes passed exception

---

build.gradle.kts
src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java
src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
src/test/java/org/openrewrite/java/logging/PrintStackTraceToLogErrorTest.java
src/test/java/org/openrewrite/java/logging/SystemErrToLoggingTest.java
src/test/java/org/openrewrite/java/logging/SystemOutToLoggingTest.java
src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java

Detect for instance `@Slf4j` in recipes that move away from `System.out`, `System.err` and `printStackTrace`.
Fixes https://github.com/openrewrite/rewrite-logging-frameworks/issues/114
Should we cover more recipes already?
We could have generically fixed this by adding synthetic log fields to the associated classes, but I figured that's harder to do for a quick win here.
- https://github.com/openrewrite/rewrite/issues/1297

Support for Lombok log annotations in three recipes

---

src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java

Display names of system.err and system.our print recipes
Confusion in the documentation. See #116

Use non-identical display names for system print recipes (#116)

---

src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
src/test/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstantTest.java

Added a `MethodMatcher` for `Object::toString()` instead of checking simple name, to avoid matching on other methods called `toString` (like `Arrays.toString(values)`)
Fixes https://github.com/moderneinc/support-app/issues/21
@knutwannheden @timtebeek

do not modify when not Object::toString()

---

src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

Log messages with a dollar sign ($) fails to parse on the `ParameterizedLogging` recipe.
Disable the recipe and refactor the code manually

Escape dollar sign on messages

---

src/main/java/org/openrewrite/java/logging/ChangeLombokLogAnnotation.java
src/main/resources/META-INF/rewrite/log4j.yml
src/main/resources/META-INF/rewrite/slf4j.yml
src/test/java/org/openrewrite/java/logging/slf4j/CommonsLoggingToSlf4j1Test.java
src/test/java/org/openrewrite/java/logging/slf4j/Log4j2ToSlf4j1Test.java

Add a new recipe `ChangeLombokLogAnnotation` and use that to migrate lombok annotations too, when switching to Log4j2 or Slf4j.
Lombok annotations were missed, leading to an incomplete migration.
`Sl4fJ` is now the default for a nullable argument. Any chance that interferes with how `getRecipeList()` returns a dynamic list?
Could have gone with explicit ChangeType recipes in Yaml, but those would have been repetitive as we add more logging frameworks, such as commons-logging last week.

Replace Lombok logging annotations when switching frameworks

---

src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
src/test/java/org/openrewrite/java/logging/SystemOutToLoggingTest.java

Add a test that brought to light a concurrent modification exception with `doAfterVisit(this)`.
Removing that statement already made all the tests we have pass.
Then followup fixes as prompted by IDE warnings, as per team convention.
Fixes #125
- #125

Fix concurrent modification exception when using JUL

---

src/main/resources/META-INF/rewrite/log4j.yml
src/test/java/org/openrewrite/java/logging/log4j/CommonsLoggingToLog4jTest.java

This PR adds a recipe to migrate from Apache Commons Logging to Log4j 2.x API: `org.openrewrite.java.logging.log4j.CommonsLoggingToLog4j`.
While it has an excellent SLF4J support `rewrite-logging-frameworks` is somehow lacking _vis-à-vis_ Log4j 2.x API support.
As part of apache/logging-log4j2#2080 we plan to cover all conversions between the most popular logging APIs and Log4j API and between the most popular logging backends and Log4j Core. I would appreciate if these recipes could be included in an official OpenRewrite artifact.

Add JCL to Log4j API migration

---

src/main/java/org/openrewrite/java/logging/log4j/ConvertJulEntering.java
src/main/java/org/openrewrite/java/logging/log4j/ConvertJulExiting.java
src/main/resources/META-INF/rewrite/log4j.yml
src/test/java/org/openrewrite/java/logging/log4j/ConvertJulEnteringTest.java
src/test/java/org/openrewrite/java/logging/log4j/ConvertJulExitingTest.java
src/test/java/org/openrewrite/java/logging/log4j/JulToLog4jTest.java

This PR converts the most commonly used JUL methods to their Log4j API equivalents:
* `Logger#getLogger`,
* all `Logger#<logging_level` methods,
* `Logger#entering`,
* `Logger#exiting`.
This is part of our apache/logging-log4j2#2080 task.
The main motivation is a user request for support (cf. apache/logging-log4j2#2083), hence the implementation of the `entering/exiting` rules.
Closes #132

Add basic JUL to Log4j API conversion

---

build.gradle.kts
src/main/resources/META-INF/rewrite/log4j.yml
src/test/java/org/openrewrite/java/logging/log4j/Slf4jToLog4jTest.java

This PR adds a rule to convert code written with SLF4J 1.x/2.x to Log4j API.
It covers:
* basic `Logger` methods,
* compatible `LogBuilder/LoggingEventBuilder` methods,
* `MDC` to `ThreadContext` conversion,
* `Marker` conversion,
* dependency switch from `slf4j-api` to `log4j-api`.
Solves part of #97: it **does** not cover conversion between Logback and Log4j Core, since the choice of a logging implementation is **totally** independent from the choice of the API.

Add SLF4J 2.x to Log4j API rewrite rule

---

src/main/resources/META-INF/rewrite/slf4j.yml

Add `log4j-slf4j2-impl` instead of `log4j-slf4j-impl`, and change any existing such dependencies.
Since we're using `latest.release` we pick up SLF4J version 2+, which needs this altered binding implementation.
- https://logging.apache.org/log4j/2.x/log4j-slf4j-impl.html

Adopt `log4j-slf4j2-impl` for SLF4 2+

---

src/main/java/org/openrewrite/java/logging/AddLogger.java
src/test/java/org/openrewrite/java/logging/SystemOutToLoggingTest.java

This produces the proper method chain to obtain a logger using JUL.
Simple bugfix.
I didn't change much, but a local build couldn't pass the two license tasks and a few tests just failed on some snakeyaml problems. But the scope of the changes is far from affecting anything there.
N/A
Unless you want a specific test that checks that code compiles there's not much to change or add of value in tests.

Fix LogManager logger call chain

---

src/main/resources/META-INF/rewrite/log4j.yml
src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java

Reorder `Log4j1ToLog4j2` recipes after report of incomplete migration

---

src/main/resources/META-INF/rewrite/log4j.yml

This documentation-only PR changes the description of the "Migrate Log4j 1.x to Log4j 2.x" recipe.
The description of the "Migrate Log4j 1.x to Log4j 2.x" recipe is incorrect.
Users might get the false impression that it mitigates the Log4Shell vulnerability. However:
- Log4j 1 was **never** affected by Log4Shell.
- only Log4j 2 Core was.
There are multiple reasons to migrate from Log4j 1, the first one is that the library is unsupported since 2015. Log4Shell mitigation is **not** one of them.

(doc) Description of Log4j 1 to Log4j 2 APi migration

---

src/main/java/org/openrewrite/java/logging/jul/LoggerLevelArgumentToMethod.java
src/main/resources/META-INF/rewrite/log4j.yml
src/test/java/org/openrewrite/java/logging/jul/LoggerLevelArgumentToMethodTest.java
src/test/java/org/openrewrite/java/logging/log4j/JulToLog4jTest.java

Convert JUL Logger Level arguments to methods

---

src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

Explanation of Changes:
Argument Handling:
A check is added to detect if the Marker argument is present.
If a Marker is detected, it ensures that it remains as the first argument.
Argument Reordering:
After constructing the new argument list, if a Marker is detected, it is added at the beginning of the newArgList.
Test Adjustments:
Ensure that your tests verify that the Marker argument remains in the correct position and that the logging message is parameterized correctly.
- Fixes #159

ParameterizedLogging recipe fixed

---

src/main/java/org/openrewrite/java/logging/slf4j/JulToSlf4jLambdaSupplierWithThrowable.java
src/main/java/org/openrewrite/java/logging/slf4j/JulToSlf4jSimpleCallsWithThrowable.java
src/main/resources/META-INF/rewrite/slf4j.yml
src/test/java/org/openrewrite/java/logging/slf4j/JulToSlf4jTest.java

Added conversion from JUL to slf4j calls that have Throwable as parameter included
Continuation of #155 and PR: https://github.com/openrewrite/rewrite-logging-frameworks/pull/160
@timtebeek

Add handling of convertion JUL to slf4j calls with Throwable; #155

---

src/main/java/org/openrewrite/java/logging/slf4j/LoggersNamedForEnclosingClass.java
src/test/java/org/openrewrite/java/logging/slf4j/LoggersNamedForEnclosingClassTest.java

Only replace known cases & only replace arguments.
Attempt to replicate a reported issue. Failed to replicate, but now limit when recipe runs and how it operates.

Simplify LoggersNamedForEnclosingClass in attempt to replicate issue

---

build.gradle.kts
src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

As [reported via Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1732921289938769).

Do not fail ParameterizedLogging for Kotlin String templates

---

src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java

Disabled `ParameterizedLogging` on Groovy files
@timtebeek @kmccarp

Disable `ParameterizedLogging` on Groovy files

---

build.gradle.kts
src/main/java/org/openrewrite/java/logging/log4j/LoggerSetLevelToConfigurator.java
src/main/resources/META-INF/rewrite/log4j.yml
src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java

- Fixes #190
- Fixes #191
- Fixes #194
- Fixes #193

Add additional steps to `Log4j1ToLog4j2`

---

src/test/java/org/openrewrite/java/logging/SystemErrToLoggingTest.java

Add testcase to validate switch cases in `SystemErrToLogging`
- Fixes https://github.com/openrewrite/rewrite-logging-frameworks/issues/192
@timtebeek

Add testcase to validate switch cases in `SystemErrToLogging`

---

src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java
src/test/java/org/openrewrite/java/logging/SystemErrToLoggingTest.java

Add testcase to validate switch cases in `SystemErrToLogging` and `ParameterizedLogging`
- https://github.com/openrewrite/rewrite/pull/4749
@timtebeek

Add testcases to validate switch cases in `SystemErrToLogging` and `ParameterizedLogging`

---

src/main/java/org/openrewrite/java/logging/LoggingFramework.java
src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java

Looks like these weren't necessary anymore, but the compilation errors they had only showed after
- https://github.com/openrewrite/rewrite/pull/4412

Drop `contextSensitive()` from `JavaTemplate` to fix compilation

---

build.gradle.kts
src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java

This does not yet work as expected in the test
Moved dependency to `compileOnly`
Vulnerability
why does the test not work? logback 1 should be on the classpath because `classpathFromResources` but it is not available:
@timtebeek @knutwannheden

Remove log4j from runtime classpath as it is only needed to generate a recipe from a refaster template

---

src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

**Only tests**
Openrewrite can [convert](https://docs.openrewrite.org/recipes/java/logging/parameterizedlogging) log statements into parameterized log statements, often yielding substantial performance gain. However, currently, loggers that are generated through a Lombok annotation, e.g., `@Slf4j`, are not supported.
- https://projectlombok.org/api/lombok/extern/slf4j/Slf4j
- https://docs.openrewrite.org/recipes/java/logging/parameterizedlogging

`ParameterizedLogging` support for logger fields added through Lombok annotations

---

src/test/java/org/openrewrite/java/logging/PrintStackTraceToLogErrorTest.java

Added more test cases.
Identify an issue with the `PrintStackTraceToLoggerError` recipe.
All the corner cases I tested for work as expected.

Add more test cases for `PrintStackTraceToLoggerError` recipe

---

src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

Removed the method call `contextSensitive()` on `JavaTemplate` though that may not be the "right" fix. Please advise.
Under certain conditions, the following exception is thrown.
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
java.base/java.util.Objects.checkIndex(Objects.java:361)
java.base/java.util.ArrayList.get(ArrayList.java:427)
org.openrewrite.java.internal.template.JavaTemplateParser.parseMethodArguments(JavaTemplateParser.java:210)
org.openrewrite.java.internal.template.JavaTemplateJavaExtension$1.visitMethodInvocat …
```

Allow parameterized logger in returned anonymous class implementation

---

src/main/java/org/openrewrite/java/logging/slf4j/WrapExpensiveLogStatementsInConditionals.java
src/main/resources/META-INF/rewrite/examples.yml

Use classpathFromResources instead of classpath

Use classpathFromResources in InexpensiveLogStatements

---

src/main/java/org/openrewrite/java/logging/slf4j/WrapExpensiveLogStatementsInConditionals.java
src/test/java/org/openrewrite/java/logging/slf4j/WrapExpensiveLogStatementsInConditionalsTest.java

Scoped autoformat better, so the recipe does not reformat lines it does not touch.

Make inexpensive log statements less noisy

---

src/main/java/org/openrewrite/java/logging/slf4j/MatchIsLogLevelEnabledWithLogStatements.java
src/main/resources/META-INF/rewrite/examples.yml
src/main/resources/META-INF/rewrite/slf4j.yml
src/test/java/org/openrewrite/java/logging/slf4j/MatchIsLogLevelEnabledWithLogStatementsTest.java

Implement a suggestion by @Knut-Ove.

Add `MatchIsLogLevelEnabledWithLogStatements` to SLF4J best practices

---

build.gradle.kts

Excluding the Spotbugs dependency
Fix the broken CI:
```
> Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve com.github.spotbugs:spotbugs-annotations:4.9.3.
Required by:
root project : > org.apache.logging.log4j:log4j-core:2.25.0
root project : > org.apache.logging.log4j:log4j-core:2.25.0 > org.apache.logging.log4j:log4j-api:2.25.0
> Dependency resolution is looking for a library compatible with JVM runtime version 8, but 'com.github.spotbugs:spotbugs-annotations:4.9.3' is only compatible with JVM runtime version 11 or newer.
```
Related to: https://github.com/apache/logging-log4j2/issues/3754
Also I don't think we need this Spotbugs at all. Not sure why they export it.

Exclude spotbugs dependency

---

src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

`MethodMatcher()` pattern doesn't match subtypes of the specified receiver
The `Parameterize logging statements` recipe has an optional feature to remove `.toString()` from the arguments that are to be parameterized. There is a bug where only the `java.lang.Object` parameters would get `.toString()` stripped, the method matcher for `toString()` is too narrow.
https://docs.openrewrite.org/reference/method-patterns#examples
Added a new test and validated on the apache repos, specifically for example [here](https://github.com/apache/opennlp/blob/3ec9e1592cf58da65a4744247e44bdb5c5d9ab70/opennlp-tools/src/main/java/opennlp/tools/parser/Parse.java#L1039-L1041)

fix: match `.toString()` on any type, not just java.lang.Object

---

src/main/java/org/openrewrite/java/logging/slf4j/StripToStringFromArguments.java
src/test/java/org/openrewrite/java/logging/slf4j/StripToStringFromArgumentsTest.java

Fixes https://github.com/openrewrite/rewrite-logging-frameworks/issues/228
In SLF4J, the last argument of the logging methods will be treated specially and removed from the formatted string argument array if it's a Throwable.
When the last argument was a `.toString()` call we stripped it even if it was a `Throwable` which changed the behaviour.
https://www.slf4j.org/faq.html#paramException

fix: any last argument matching `Throwable.toString()` is left as is

---

src/main/java/org/openrewrite/java/logging/slf4j/WrapExpensiveLogStatementsInConditionals.java
src/test/java/org/openrewrite/java/logging/slf4j/WrapExpensiveLogStatementsInConditionalsTest.java

`WrapExpensiveLogStatementsInConditionals` is now checking if all log call arguments are getters. When they are, those operations are considered inexpensive and the log call is left as is, unwrapped.
- Fix #232 
@timtebeek 
@greg-at-moderne

Don't if-wrap logs when arguments are getters

---

src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java

Handle existing arguments alongside concatenation in `ParameterizedLogging`

---

src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
src/test/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstantTest.java

This PR changes the behavior of the `Slf4jLogShouldBeConstant` recipe where it was converting `String.format()` calls that contained format specifiers with width, alignment, or precision modifiers.
The recipe was stripping all formatting information, breaking columnar output in logs.
The new regex could use scrutiny.
For recipe groups like CommonStaticAnalysis, I [split it up](https://github.com/liftwizard/liftwizard/blob/5c3f313a59cf3ee4e7e3967df80c6e80778da3fb/liftwizard-maven-build/liftwizard-profile-parent/pom.xml#L129) and remove the problematic recipes, but this one is a leaf.
As I was preparing this PR, I saw #238 and I figured I'd get this out quicker for discussion. The main thing I was surprised at is the other PR title makes it sound like String.format strings are not getting …

Fix Slf4jLogShouldBeConstant to preserve format specifiers with width, alignment, and precision.

---

src/main/java/org/openrewrite/java/logging/slf4j/JulParameterizedArguments.java
src/test/java/org/openrewrite/java/logging/slf4j/JulParameterizedArgumentsTest.java

The `org.openrewrite.java.logging.slf4j.JulParameterizedArguments` recipe now supports migrating `JUL.log("{0}", arrayIdentifier)` to SLF4J.
Before that the only supported form was: `JUL.log("{0}", new String[]{"foo"})`.

Avoid unsafe changes in `JulParameterizedArguments` when `JavaType.Array` argument is not a `J.NewArray`
