openrewrite/rewrite-logging-frameworks

- src/main/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogback.java
- src/main/java/org/openrewrite/java/logging/logback/Log4jLayoutToLogback.java
- src/main/java/org/openrewrite/java/logging/logback/package-info.java
- src/main/java/org/openrewrite/java/logging/slf4j/Log4jToSlf4j.java
- src/main/java/org/openrewrite/java/logging/slf4j/package-info.java
- src/main/resources/META-INF/rewrite/logback.yml
- src/main/resources/META-INF/rewrite/slf4j.yml
- src/test/kotlin/org/openrewrite/java/logging/logback/Log4jAppenderToLogbackTest.kt
- src/test/kotlin/org/openrewrite/java/logging/logback/Log4jLayoutToLogbackTest.kt
- src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4jToSlf4jTest.kt
closes https://github.com/openrewrite/rewrite-logging/issues/4
Puts content in packages closer in semblance to how we organize content in other projects.
Still due to some re-assessment, of course. But, it's putting out the scaffolding 👍
> Preliminary package organization

- src/main/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogback.java
- src/test/kotlin/org/openrewrite/java/logging/logback/Log4jAppenderToLogbackTest.kt
- src/test/kotlin/org/openrewrite/java/logging/logback/Log4jLayoutToLogbackTest.kt
Part of https://github.com/openrewrite/rewrite-logging/issues/3
> Polish Log4jAppenderToLogbackTest and Log4jLayoutToLogbackTest

- src/main/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogback.java
- src/main/java/org/openrewrite/java/logging/logback/Log4jLayoutToLogback.java
- src/test/kotlin/org/openrewrite/java/logging/logback/Log4jAppenderToLogbackTest.kt
- src/test/kotlin/org/openrewrite/java/logging/logback/Log4jLayoutToLogbackTest.kt
part of https://github.com/openrewrite/rewrite-logging/issues/9
> Refactor Log4jToLogback to be more contemporary

- src/main/java/org/openrewrite/java/logging/slf4j/Log4jToSlf4j.java
- src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4jToSlf4jTest.kt
part of https://github.com/openrewrite/rewrite-logging/issues/16
> use java.lang.Object as any() type parameter for Log4jToSlf4j

- src/main/java/org/openrewrite/java/logging/slf4j/ParameterizedLogging.java
- src/test/kotlin/org/openrewrite/java/logging/slf4j/ParameterizedLoggingTest.kt
closes https://github.com/openrewrite/rewrite-logging-frameworks/issues/26
> handle arguments containing binary expressions

- src/main/java/org/openrewrite/java/logging/slf4j/Log4jToSlf4j.java
- src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4jToSlf4jTest.kt
Additional tests and content based on usage.
> Handle method invocations as arguments

- src/main/java/org/openrewrite/java/logging/slf4j/ParameterizedLogging.java
- src/test/kotlin/org/openrewrite/java/logging/slf4j/ParameterizedLoggingTest.kt
part of https://github.com/openrewrite/rewrite-logging-frameworks/issues/30
> Escape templating strings

- build.gradle.kts
- src/main/java/org/openrewrite/java/logging/slf4j/Log4j2ToSlf4j.java
- src/test/kotlin/org/openrewrite/java/logging/slf4j/Log4j2ToSlf4jTest.kt
Part of https://github.com/openrewrite/rewrite-logging-frameworks/issues/43
The existing recipe details a migration from Log4j1 to SLF4J, whereas this recipe specifically pertains to Log4J2 to SLF4J
> Log4j2 to SLF4J

- src/main/java/org/openrewrite/java/logging/slf4j/LoggersNamedForEnclosingClass.java
- src/test/kotlin/org/openrewrite/java/logging/slf4j/LoggersNamedForEnclosingClassTest.kt
Fixes https://github.com/openrewrite/rewrite-logging-frameworks/issues/65
> Loggers named for enclosing class

- src/main/resources/META-INF/rewrite/slf4j.yml
- src/test/kotlin/org/openrewrite/java/logging/slf4j/Slf4jBestPracticesTest.kt
> add Slf4j Best Practices recipe

- src/main/resources/META-INF/rewrite/log4j.yml
> recipe Log4j1ToLog4j2 removes reload4j dependency

- suppressions.xml
Reverts openrewrite/rewrite-logging-frameworks#80
> Revert "chore: update jackson"

- src/test/java/org/openrewrite/java/logging/slf4j/CompleteExceptionLoggingTest.java
I'm not entirely certain about this, but, I hope I'm right...
> spelling: times

- src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
- src/test/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstantTest.java
Fixes https://github.com/openrewrite/rewrite-logging-frameworks/issues/89#issuecomment-1556192263
> Support toString without select in Slf4jLogShouldBeConstant

- src/test/java/org/openrewrite/java/logging/AddLoggerTest.java
- src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java
- src/test/java/org/openrewrite/java/logging/PrintStackTraceToLogErrorTest.java
- src/test/java/org/openrewrite/java/logging/SystemErrToLoggingTest.java
- src/test/java/org/openrewrite/java/logging/SystemOutToLoggingTest.java
- src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java
- src/test/java/org/openrewrite/java/logging/log4j/PrependRandomNameTest.java
- src/test/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogbackTest.java
- src/test/java/org/openrewrite/java/logging/logback/Log4jLayoutToLogbackTest.java
- src/test/java/org/openrewrite/java/logging/slf4j/Log4j1ToSlf4j1Test.java
- src/test/java/org/openrewrite/java/logging/slf4j/Log4j2ToSlf4j1Test.java
- src/test/java/org/openrewrite/java/logging/slf4j/Slf4jBestPracticesTest.java
- src/test/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstantTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.recipes.SelectRecipeExamples?organizationId=T3BlblJld3JpdGU%3D
> refactor: Automatically select recipe examples from the unit test cases of a recipe

- src/main/java/org/openrewrite/java/logging/LoggingFramework.java
- src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java
- src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
- src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
- src/main/java/org/openrewrite/java/logging/SystemPrintToLogging.java
- src/main/java/org/openrewrite/java/logging/log4j/PrependRandomName.java
- src/main/java/org/openrewrite/java/logging/logback/Log4jAppenderToLogback.java
- src/main/java/org/openrewrite/java/logging/slf4j/Slf4jLogShouldBeConstant.java
Remove unused arguments & methods where we override a default.
Less to read & maintain; make intentional changes stand out.
> Minor cleanup following #121

- src/main/java/org/openrewrite/java/logging/log4j/ConvertJulEntering.java
- src/main/java/org/openrewrite/java/logging/log4j/ConvertJulExiting.java
- src/test/java/org/openrewrite/java/logging/log4j/Log4j1ToLog4j2Test.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.OpenRewriteBestPractices?organizationId=T3BlblJld3JpdGU%3D
> refactor: OpenRewrite best practices

- src/main/java/org/openrewrite/java/logging/log4j/LoggingExceptionConcatenation.java
- src/main/resources/META-INF/rewrite/log4j.yml
- src/test/java/org/openrewrite/java/logging/log4j/LoggingExceptionConcatenationTest.java
This adds missing licenses and fixes some malformatted yaml.
Get #145 going by way of making current build stable.
No.
@timtebeek I guess to make this easier
N/A.
No tests were added, build passing is proof enough I hope.
> Add missing licenses and fix malformatted yml.

- src/main/java/org/openrewrite/java/logging/AddLogger.java
- src/test/java/org/openrewrite/java/logging/AddLoggerTest.java
Because of reported compilation errors with static fields in inner classes.
> Inner classes should have non static logger field

- suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/709
> chore: remove common OR suppressions

- src/main/java/org/openrewrite/java/logging/ChangeLombokLogAnnotation.java
- src/main/java/org/openrewrite/java/logging/LoggingFramework.java
- src/main/java/org/openrewrite/java/logging/ParameterizedLogging.java
- src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java
- src/main/java/org/openrewrite/java/logging/SystemErrToLogging.java
- src/main/java/org/openrewrite/java/logging/SystemOutToLogging.java
- src/main/java/org/openrewrite/java/logging/SystemPrintToLogging.java
- src/main/java/org/openrewrite/java/logging/log4j/package-info.java
- src/main/java/org/openrewrite/java/logging/logback/package-info.java
- src/main/java/org/openrewrite/java/logging/package-info.java
- src/main/java/org/openrewrite/java/logging/slf4j/ChangeLogLevel.java
- src/main/java/org/openrewrite/java/logging/slf4j/CompleteExceptionLogging.java
- src/main/java/org/openrewrite/java/logging/slf4j/JulParameterizedArguments.java
- src/main/java/org/openrewrite/java/logging/slf4j/package-info.java
Use this link to re-run the recipe: https://app.moderne.io/builder/gW3xaSLWV?organizationId=T3BlblJld3JpdGU%3D
> Migrate to JSpecify from OpenRewrite JSR-305 meta-annotations

- suppressions.xml
Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/741
> update suppressions for 09-25-2024 vulnerability report

- build.gradle.kts
- suppressions.xml
related to:
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/776
> chore: update suppressions

- suppressions.xml
- related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/781
> chore: update OWASP suppressions

- src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java
Added test for reported issue 
- Closes https://github.com/openrewrite/rewrite-logging-frameworks/issues/167
Not reproducible
> Test for marker and lambda

- src/main/resources/META-INF/rewrite/slf4j.yml
add dependency changes to `CommonsLogging1ToSlf4j1`
Handle dependency updates
Custom recipes.
> Switch Dependencies migrating ACL -> SLF4J

- src/main/java/org/openrewrite/java/logging/slf4j/WrapExpensiveLogStatementsInConditionals.java
- src/main/resources/META-INF/rewrite/examples.yml
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
> OpenRewrite recipe best practices
